export enum Role {
  ADMIN = "8",
  USER = "4",
  AUTHOR = "9"
}

export enum Errors {
  UNAUTHORIZED = "UNAUTHORIZED",
  NO_SESSION_FOUND = "NO_SESSION_FOUND",
  ACCESS_DENIED = "ACCESS_DENIED",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  TOKEN_MALFORMED = "TOKEN_MALFORMED",
  NO_TOKEN_PROVIDED = "NO_TOKEN_PROVIDED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  WRONG_CREDENTIALS = "WRONG_CREDENTIALS",
  ONLY_FOR_TEST = "ONLY_FOR_TEST",
  ALREADY_EXISTS = "ALREADY_EXISTS",
  REDIS_CONNECTION_ERROR = "REDIS_CONNECTION_ERROR",
  MONGO_CONNECTION_ERROR = "MONGO_CONNECTION_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  NOT_FOUND = "NOT_FOUND"
}
